---
title: "DataExploration"
output:
  html_document: default
  word_document: default
  pdf_document: default
---
### 1A. Two scatter plots of two different variables
```{r Two scatter plots of two different variables (1A), echo=FALSE}

 library(tidyverse)
 library(ggplot2)
 LLNF <- read.csv("Site_H.csv", header = TRUE)
 colnames(LLNF)
 names(LLNF)[names(LLNF) == "Date.Time..GMT.04.00"] <- "DateTime"
 names(LLNF)[names(LLNF) == "Temp..Â.C..LGR.S.N..10638853..SEN.S.N..10638853."] <- "Temperature"
 names(LLNF)[names(LLNF) == "Intensity..Lux..LGR.S.N..10638853..SEN.S.N..10638853."] <- "Intensity"
 ggplot(LLNF,aes(x=Temperature,y=Intensity))+
 geom_point(color="Dark blue")
```
 
 
### 1B.Two scatter plots of two different variables 
```{r Two scatter plots of two different variables (1B) , echo=FALSE}
 
LLNF$DateTime <- as.Date(LLNF$DateTime,format("%m/%d/%y"))
ggplot(LLNF,aes(x=DateTime,y=Intensity))+
geom_point(color="Dark blue")
```

### 2) One scatter plot with three variables
```{r One scatter plot with three variables, echo=FALSE}
 ggplot(LLNF,aes(x=DateTime,y=Intensity,color=Temperature))+
 geom_point()

```

### 3) One scatter plot of two variables, properly labeled, with a trend line added in
```{r One scatter plot of two variables, properly labeled, with a trend line added in, echo=FALSE}
 ggplot(LLNF,aes(x=Temperature,y=Intensity))+
 geom_point()+
 geom_smooth(method="lm")
```

### 4) One faceted plot of two variables
```{r One faceted plot of two variables, echo=FALSE}
LLNF1<-gather(LLNF,key="measure",value="value",c(Intensity,Temperature))
 ggplot(LLNF1,aes(x=DateTime,y=value))+
 geom_point()+
 facet_wrap(~measure)+
 theme_bw()
```

### 5) One bar chart
```{r One bar chart, echo=FALSE}

 ggplot(LLNF,aes(x=DateTime,y=Temperature,fill="grp"))+
 geom_bar(stat="identity",color="blue",width=0.5)
```
